#!/usr/bin/env python3
# BadgeBoy - Game Boy / Game Boy Color emulator for the GitHub Universe badge
# Copyright (C) 2026 Anas Khan
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Convert a Game Boy / Game Boy Color ROM into a C header that embeds the ROM
# as a flash-resident array. CMake calls this automatically; you can also run it
# by hand to inspect a ROM's header.
#
#   python3 tools/rom2c.py <input.gb|.gbc> <output.h>
#
# The generated header declares:
#   const unsigned char gb_rom[];
#   #define GB_ROM_SIZE <n>
#
# The output contains copyrighted game data and is never committed. Supply only
# ROMs you legally own.

import os
import re
import sys

CART_TYPES = {
    0x00: "ROM ONLY", 0x01: "MBC1", 0x02: "MBC1+RAM", 0x03: "MBC1+RAM+BATTERY",
    0x0F: "MBC3+TIMER+BATTERY", 0x10: "MBC3+TIMER+RAM+BATTERY", 0x11: "MBC3",
    0x12: "MBC3+RAM", 0x13: "MBC3+RAM+BATTERY",
    0x19: "MBC5", 0x1A: "MBC5+RAM", 0x1B: "MBC5+RAM+BATTERY",
    0x1C: "MBC5+RUMBLE", 0x1D: "MBC5+RUMBLE+RAM", 0x1E: "MBC5+RUMBLE+RAM+BATTERY",
}


def display_title(path: str, data: bytes) -> str:
    """A clean menu name from the file name, falling back to the cart header."""
    name = os.path.splitext(os.path.basename(path))[0]
    name = re.sub(r"[\(\[].*?[\)\]]", "", name)
    name = name.replace("_", " ").replace(" - ", " ")
    name = re.sub(r"\s+", " ", name).strip(" -")
    if not name:
        raw = data[0x134 : (0x13F if (data[0x143] & 0x80) else 0x143)]
        name = "".join(chr(b) for b in raw if 0x20 <= b < 0x7F).strip()
    return (name or "Game")[:31]


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: rom2c.py <input.gb|.gbc> <output.h>", file=sys.stderr)
        return 2

    src, out = sys.argv[1], sys.argv[2]
    with open(src, "rb") as f:
        data = f.read()

    if len(data) < 0x150:
        print(f"error: {src} is too small to be a valid ROM", file=sys.stderr)
        return 1

    title = data[0x134:0x143].split(b"\x00")[0].decode("ascii", "replace").strip()
    cgb_flag = data[0x143]
    cart_type = data[0x147]
    cgb = "GBC only" if cgb_flag == 0xC0 else ("GBC enhanced" if cgb_flag == 0x80 else "DMG")
    menu_title = display_title(src, data).replace('"', "'")

    out_dir = os.path.dirname(out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    with open(out, "w") as o:
        o.write("// Generated by tools/rom2c.py. Do not edit. Do not commit.\n")
        o.write(f"// Title: {title!r}  Mode: {cgb}  "
                f"Cartridge: {CART_TYPES.get(cart_type, hex(cart_type))}  "
                f"Size: {len(data)} bytes\n")
        o.write("#ifndef GB_ROM_H\n#define GB_ROM_H\n")
        o.write(f"#define GB_ROM_SIZE {len(data)}u\n")
        o.write(f'#define GB_ROM_TITLE "{menu_title}"\n')
        o.write('__attribute__((section(".rodata"))) const unsigned char gb_rom[] = {\n')
        for i in range(0, len(data), 16):
            o.write("  " + ",".join(str(b) for b in data[i:i + 16]) + ",\n")
        o.write("};\n#endif // GB_ROM_H\n")

    print(f"rom2c: {title!r} [{cgb}, {CART_TYPES.get(cart_type, hex(cart_type))}], "
          f"{len(data)} bytes -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
